# Generated by Django 5.1.1 on 2024-09-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hiroes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="spell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=31)),
                ("hp_increase", models.IntegerField()),
                ("ap_increase", models.FloatField()),
                ("dp_increase", models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name="warrior",
            name="hit",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="warrior",
            name="name",
            field=models.CharField(max_length=31),
        ),
    ]
