# Generated by Django 5.1.1 on 2024-10-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hiroes", "0002_spell_warrior_hit_alter_warrior_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="warrior",
            name="image",
            field=models.ImageField(default=0, upload_to="images"),
        ),
    ]
